"""
Django settings for backend_python_votopia project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-45f3j6r$09!t$$rg-p_9#q0pmzj_!uo1!7%j+fljtp-c_m^^vu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# API REST Configuration
APPEND_SLASH = False  # Per API REST: accetta URL senza trailing slash

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'votopia_backend.apps.VotopiaBackendConfig',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'votopia_backend.middleware.JWTAuthenticationMiddleware',  # JWT Auth middleware
]

ROOT_URLCONF = 'backend_python_votopia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_python_votopia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME", "votopia_db"),
        'USER': os.getenv("DB_USER", "root"),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "3306"),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Permetti al server di avviarsi anche senza connessione DB
# Utile per testing e sviluppo
DATABASE_ROUTERS = []


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Autenticazione gestita manualmente nelle views con get_user_from_token()
    # Rimosso DEFAULT_AUTHENTICATION_CLASSES per evitare conflitti con il modello User personalizzato
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Votopia API",
    "DESCRIPTION": """
    ## Sistema di Gestione Votazioni, Utenti e Ruoli
    
    ### Autenticazione
    Questa API utilizza JWT (JSON Web Tokens) per l'autenticazione.
    
    **Per autenticarti:**
    1. Effettua il login tramite `/api/auth/login/` con email e password
    2. Riceverai un token `access` e un token `refresh`
    3. Clicca sul pulsante "Authorize" 🔒 in alto a destra
    4. Inserisci il token nel formato: `Bearer <il_tuo_token_access>`
    5. Clicca "Authorize" e poi "Close"
    
    Ora puoi testare tutti gli endpoint protetti!
    
    ### Sistema di Permessi
    Gli endpoint richiedono permessi specifici basati su ruoli:
    - **Organizzazione**: Permessi globali per l'intera organizzazione
    - **Lista**: Permessi limitati a liste specifiche
    
    ### Note Importanti
    - I token JWT scadono dopo 60 minuti
    - Usa `/api/token/refresh/` per rinnovare il token
    - Alcuni endpoint sono pubblici (login, health check)
    - Gli errori 401 indicano autenticazione mancante
    - Gli errori 403 indicano permessi insufficienti
    """,
    "VERSION": "1.0.0",
    "CONTACT": {
        "name": "Votopia Support",
        "email": "support@votopia.com"
    },
    "LICENSE": {
        "name": "Proprietary"
    },

    # Opzioni generali
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,

    # File locali per UI (migliora prestazioni e funzionamento offline)
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",

    # Configurazioni UI Swagger
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,  # Mantiene il token anche dopo il refresh della pagina
        "displayOperationId": True,
        "filter": True,  # Abilita la ricerca
        "defaultModelsExpandDepth": 2,
        "defaultModelExpandDepth": 2,
        "docExpansion": "list",  # Espande solo i tag, non le operazioni
        "showExtensions": True,
        "showCommonExtensions": True,
    },

    # Configurazione autenticazione JWT
    "SECURITY": [{"BearerAuth": []}],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Inserisci il token JWT nel formato: Bearer <token>"
            }
        }
    },

    # Migliora la generazione dello schema
    "SCHEMA_PATH_PREFIX": "/api/",
    "CAMELIZE_NAMES": False,
    "SORT_OPERATIONS": False,
    "SORT_OPERATION_PARAMETERS": True,

    # Gestione errori
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Development server"},
    ],

    # Tag per raggruppamento
    "TAGS": [
        {"name": "System", "description": "Endpoint di sistema (health check)"},
        {"name": "Autenticazione", "description": "Login, token JWT e gestione sessioni"},
        {"name": "Utenti", "description": "CRUD utenti e gestione profili"},
        {"name": "Ruoli", "description": "Gestione ruoli e permessi"},
        {"name": "Liste", "description": "Gestione liste elettorali"},
        {"name": "Organization", "description": "Gestione organizzazioni"},
        {"name": "Files", "description": "Upload e gestione file"},
    ],

    # Preprocessing per miglioramenti automatici
    "PREPROCESSING_HOOKS": [],
    "POSTPROCESSING_HOOKS": [],
}